### ISSUE TITLE
Error when trying to run PasteIntoFile.exe in tray mode

### ISSUE THREAD

**Issue by shimbone** [eltos/PasteIntoFile#65]
Even though a startup item was being registered (to run PasteIntoFile.exe tray), PasteIntoFile.exe was not being started.

I tried running "PasteIntoFile.exe tray" from a command shell in the PasteIntoFile directory and I got the following error:

Unhandled Exception: System.InvalidOperationException: Couldn't register the hot key.
   at PasteIntoFile.KeyboardHook.RegisterHotKey(ModifierKeys modifier, Keys key) in D:\a\PasteIntoFile\PasteIntoFile\PasteIntoFile\KeyboardHook.cs:line 81
   at PasteIntoFile.Program.RunTray(ArgsTray args) in D:\a\PasteIntoFile\PasteIntoFile\PasteIntoFile\Main.cs:line 264
   at PasteIntoFile.Program.<>c.<Main>b__8_5(ArgsTray opts) in D:\a\PasteIntoFile\PasteIntoFile\PasteIntoFile\Main.cs:line 144
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
   at PasteIntoFile.Program.Main(String[] args) in D:\a\PasteIntoFile\PasteIntoFile\PasteIntoFile\Main.cs:line 139

**To Reproduce**

1. Install PasteIntoFile
2. From a command shell navigate to C:\Program Files (x86)\PasteIntoFile
3. Run PasteIntoFile.exe tray

```
...
```

**Error message**

```
...
```

**Screenshots**

**Environment**

- App version: 
- OS: 
- ...

**Solution approach / workarounds**

...

**Comment by eltos** [comment]
> To Reproduce
    1. Install PasteIntoFile
    2. From a command shell navigate to C:\Program Files (x86)\PasteIntoFile
    3. Run PasteIntoFile.exe tray

Cannot reproduce, works for me as expected.  
Please provide sufficient information to reproduce the issue.

**Comment by shimbone** [comment]
More detailed rundown on what I'm doing to see the problem:


   - Downloaded latest version
   https://github.com/eltos/PasteIntoFile/releases
      - PasteIntoFile_v5.4_installer.msi
   - Ran installer with selected options:
      - Paste into file
      - Copy file content
      - Enable autosave
      - Autosave may open explorer (e.g. when … )
      - Autostart into tray
      - Enable clibboard patching (experimental)
      - All other options not listed are not selected.
   - Opened command prompt to C:\Program Files (x86)\PasteIntoFile
   - Ran PasteIntoFile.exe tray
   - Got the following error:

C:\Program Files (x86)\PasteIntoFile>

Unhandled Exception: System.InvalidOperationException: Couldn't register
the hot key.

   at PasteIntoFile.KeyboardHook.RegisterHotKey(ModifierKeys modifier, Keys
key) in D:\a\PasteIntoFile\PasteIntoFile\PasteIntoFile\KeyboardHook.cs:line
81

   at PasteIntoFile.Program.RunTray(ArgsTray args) in
D:\a\PasteIntoFile\PasteIntoFile\PasteIntoFile\Main.cs:line 264

   at PasteIntoFile.Program.<>c.<Main>b__8_5(ArgsTray opts) in
D:\a\PasteIntoFile\PasteIntoFile\PasteIntoFile\Main.cs:line 144

   at
CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1
result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2
parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)

   at PasteIntoFile.Program.Main(String[] args) in
D:\a\PasteIntoFile\PasteIntoFile\PasteIntoFile\Main.cs:line 139

   - Note that running without the command line option "tray" results in
   the program launching properly
